name: Whispering
options:
  bundleIdPrefix: com.rudrankriyam
  deploymentTarget:
    macOS: 14.0
  xcodeVersion: "15.0"
packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    branch: main
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    version: 4.2.2

targets:
  Whispering:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rudrankriyam.whispering
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/Whispering.entitlements
        INFOPLIST_FILE: Sources/Info.plist
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "We need access to your microphone to record audio for transcription"
        INFOPLIST_KEY_NSAppleEventsUsageDescription: "Whispering needs accessibility access to listen for the F5 key to start/stop recording."
        INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription: "We need Bluetooth access to use AirPods for audio recording"
    dependencies:
      - package: WhisperKit
      - package: KeychainAccess
